#!/usr/bin/env sh

normal() {
    if command -v nvim /dev/null 2>&1; then

        ins_ver=$(nvim --version | sed -n 1p | grep -E -o 'v(.*)')
        latest_version=$(curl -Ls -o /dev/null -w %\{url_effective\} https://github.com/neovim/neovim/releases/latest | rev | cut -f 1 -d '/' | rev)

        echo "Installed version = $ins_ver"
        echo "Latest version    = $latest_version"

        echo 'Do you want to install ? (y/N)'
        read -r choice

        if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
            curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
            rm -rf "$optdir/nvim-linux64"
            tar -C "$optdir" -xzf nvim-linux64.tar.gz
            rm -rf nvim-linux64.tar.gz
            rm -rf "$optdir/bin/nvim"
            ln -s "$optdir/nvim-linux64/bin/nvim" "$optdir/bin/"
        fi

    else
        echo 'Do you want to install ? (y/N)'
        read -r choice
        if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
            curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
            rm -rf "$optdir/nvim-linux64"
            tar -C "$optdir" -xzf nvim-linux64.tar.gz
            rm -rf nvim-linux64.tar.gz
            rm -rf "$optdir/bin/nvim"
            ln -s "$optdir/nvim-linux64/bin/nvim" "$optdir/bin/"
        fi
    fi
}

appimage() {
    if command -v nvim /dev/null 2>&1; then
        ins_ver=$(nvim --version | sed -n 1p | grep -E -o 'v(.*)')
        latest_version=$(curl -Ls -o /dev/null -w %\{url_effective\} \
            https://github.com/neovim/neovim-releases/releases/latest | rev | cut -f 1 -d '/' | rev)
        echo "Installed version = $ins_ver"
        echo "Latest version    = $latest_version"

        echo 'Do you want to install ? (y/N)'
        read -r choice

        if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
            rm -f "$optdir/nvim.appimage"
            curl -LO https://github.com/neovim/neovim-releases/releases/latest/download/nvim.appimage \
                -o "$optdir/nvim.appimage"
            chmod u+x "$optdir/nvim.appimage"
            cd "$optdir/" || exit
            rm -rf "squashfs-root"
            ./nvim.appimage --appimage-extract
        fi

    else
        echo 'Do you want to install ? (y/N)'
        read -r choice

        if [ "$choice" = "y" ] || [ "$choice" = "Y" ]; then
            curl -LO https://github.com/neovim/neovim-releases/releases/latest/download/nvim.appimage \
                -o "$optdir/nvim.appimage"
            chmod u+x "$optdir/nvim.appimage"
            cd "$optdir/" || exit
            ./nvim.appimage --appimage-extract
        fi
    fi
}

# parse argv variables

check=""
optdir="$HOME/opt"
while [ "$#" -gt 0 ]; do
    case "$1" in
    --appimage)
        appimage
        shift 1
        check="1"
        ;;
    --main)
        normal
        shift 1
        check="1"
        ;;
    --opt)
        optdir="$2"
        shift 2
        ;;
    -h | --help)
        usage
        exit
        ;;
    *)
        normal
        ;;
    esac
done

if [ -n "$check" ]; then
    :
else
    echo "Choose a variant, either --appimage(unsupported/old glibc) or --main(supported/main)"
fi
